version: 2
commands:
  fullname:
    description: "A very simple command that reveals my full name"
    parameters:
      to:
        type: string
        default: "Ayorinde G. Smart"
    steps:
      - run: echo << parameters.to >>
      
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}


jobs:
  one:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
          
  three:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - print_pipeline_id
      - checkout
      - run: echo " My name is $My_Global_Name "
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace
      
workflows:
  version: 2
  one_two_and_three:
    jobs:
      - three
      - one
      - two:
          requires:
            - one
